blank_issues_enabled: false
contact_links:
  - name: Sicherheitslücke melden
    url: https://github.com/BlackRabbitZ/kvm-qemu-safebox/security
    about: Bitte sicherheitskritische Schwachstellen nach Möglichkeit privat melden.
