#!/usr/bin/env python3
"""Normalize libvirt nwfilter XML before integrity comparison.

Only the autogenerated UUID and purely representational whitespace differ.
Changes to rule/priority/action/attribute text affect the digest.
"""
import hashlib
import sys
import xml.etree.ElementTree as ET


def normalize(el):
    attrs = dict(sorted(el.attrib.items()))
    el.attrib.clear()
    el.attrib.update(attrs)
    if not (el.text or '').strip():
        el.text = None
    if not (el.tail or '').strip():
        el.tail = None
    for child in el:
        normalize(child)


def main():
    root = ET.parse(sys.stdin).getroot()
    if root.tag != 'filter':
        raise ValueError('Kein nwfilter-Dokument')
    for child in list(root):
        if child.tag == 'uuid':
            root.remove(child)
    normalize(root)
    print(hashlib.sha256(ET.tostring(root, encoding='utf-8')).hexdigest())


if __name__ == '__main__':
    main()
